Support global.json's rollForward latest* variants
actions/setup-dotnet pull request #538
Opened 2024-07-20 22:55 UTC by js6pak

**Description:**
This PR is a cleaned up version of #481, which fixes 2 issues:
1. In the original `npm run build` wasn't rerun so `dist` is stale there
2. The tests that were added never passed successfully

There are 3 additional commits in this PR:
1. https://github.com/actions/setup-dotnet/commit/b4737b42ef4939bca196a752410e007bbcda3ee6 which fixes the 6 minute delay on windows runners caused by `clear-toolcache.ps1`
2. https://github.com/actions/setup-dotnet/commit/18b9c2a2769b108ffd036965ce138bf6993fc91b which makes sure the `Uses an up to date bash download script` test passes
3. https://github.com/actions/setup-dotnet/commit/3f75cd0094569fa290b49ab70ef4cf769c406aef makes sure tests run even before the PR workflow is manually accepted, this can be dropped if needed

**Related issue:**
Fixes #448, closes #481

**Check list:**
- [ ] Mark if documentation changes are required.
- [x] Mark if tests were added or updated to cover the changes.

2024-08-06 14:35 UTC, js6pak commented
@HarithaVattikuti

2025-05-01 18:38 UTC, js6pak commented
@HarithaVattikuti bump

2026-05-06 06:40 UTC, v-priyagupta108 commented
Hi @js6pak,

Thank you for this contribution, this fills an important gap in `global.json` support! Here are a few review points:

1. **Rebase onto latest `main`.** This will ensure your changes are up-to-date with the current codebase.

2. **Revert the workflow trigger changes.** The branch filter removals across the CI workflow files (`.github/workflows/*.yml`) appear unrelated to this feature. Please revert those so they remain as-is.

Once those are addressed, happy to take another look. Thanks!

2026-05-07 21:48 UTC, js6pak commented
@priyagupta108 I've rebased the PR, so you can take a look. Workflow trigger changes are needed for external contributors to test whether their changes pass CI, so I'd recommend keeping them, but if you want to drop it, I'd do it after making sure you don't want any other changes to the actual feature (so I can test that CI works after requested changes :v).

2026-05-08 13:25 UTC, js6pak commented
@priyagupta108 Note the `Basic validation` workflow is broken on the `main` branch: https://github.com/actions/setup-dotnet/actions/workflows/basic-validation.yml?query=branch%3Amain, so it's unrelated to this PR.

2026-05-18 09:05 UTC, v-priyagupta108 commented
Hi @js6pak, thanks for the quick rebase!

A few follow-up items to address:

1. **`__tests__/e2e-test-csproj` changes:** Migrating the entire test project from MSTest to Newtonsoft.Json just to support a single `latestMinor` test case feels like a significant change, especially since that test depends on .NET Core 3.1, which has been EOL since December 2022. Would you consider reverting the migration and dropping the `latestMinor` test instead?

2. **`actions/checkout` version:** Some of the new jobs added in `e2e-tests.yml` still use `actions/checkout@v3`. Could these be updated to `actions/checkout@v6` to match the rest of the workflow?

3. **Branch filters:** The current branch filters (`main`, `releases/*`) are intentional because they prevent CI from running on every push to every branch, which helps keep workflow costs and noise low for the repo. Could you please drop this change from the PR once your testing is complete?

Once those are addressed, happy to continue the review. Thanks!

2026-05-21 00:26 UTC, js6pak commented
> A few follow-up items to address:
> 
> 1. **`__tests__/e2e-test-csproj` changes:** Migrating the entire test project from MSTest to Newtonsoft.Json just to support a single `latestMinor` test case feels like a significant change, especially since that test depends on .NET Core 3.1, which has been EOL since December 2022. Would you consider reverting the migration and dropping the `latestMinor` test instead?
> 2. **`actions/checkout` version:** Some of the new jobs added in `e2e-tests.yml` still use `actions/checkout@v3`. Could these be updated to `actions/checkout@v6` to match the rest of the workflow?
> 3. **Branch filters:** The current branch filters (`main`, `releases/*`) are intentional because they prevent CI from running on every push to every branch, which helps keep workflow costs and noise low for the repo. Could you please drop this change from the PR once your testing is complete?
> 
> Once those are addressed, happy to continue the review. Thanks!

Thanks for catching 2., I disagree with 1. and 3. but addressed them.

2026-05-22 09:30 UTC, priyagupta108 approved these changes

2026-05-22 09:48 UTC, priya-kinthali approved these changes

2026-05-26 22:43 UTC, HarithaVattikuti approved these changes

2026-05-26 22:43 UTC, merged

2026-05-28 09:46 UTC, nikita-bestuzhev-ct commented
@HarithaVattikuti, @priyagupta108, hello!

JFYI, the following `global.json`:
```
{
  "sdk": {
    "version": "8.0",
    "rollForward": "latestFeature"
  }
}
```
now fails with:
`Error: Cannot read properties of undefined (reading 'substring')`

See https://github.com/actions/setup-dotnet/pull/538/changes#diff-83766f6dc1065d750be380c25c707c33a1516e036ef73f08764fbbb9cb9048a7R212

Was it done intentionally?

2026-05-28 09:55 UTC, otemnov commented
@nikita-bestuzhev-ct I've opened an issue https://github.com/actions/setup-dotnet/issues/739

2026-05-28 12:33 UTC, Frulfump commented
> @HarithaVattikuti, @priyagupta108, hello!
> 
> JFYI, the following `global.json`:
> ```
> {
>   "sdk": {
>     "version": "8.0",
>     "rollForward": "latestFeature"
>   }
> }
> ```
> now fails with:
> `Error: Cannot read properties of undefined (reading 'substring')`
> 
> See https://github.com/actions/setup-dotnet/pull/538/changes#diff-83766f6dc1065d750be380c25c707c33a1516e036ef73f08764fbbb9cb9048a7R212
> 
> Was it done intentionally?

8.0 isn't a valid version according to the docs for global.json https://learn.microsoft.com/en-us/dotnet/core/tools/global-json#version 


>version
>
>    Type: string
>
>The version of the .NET SDK to use.
>
>This field:
>
>    Requires the full version number, such as 10.0.100.
>    Doesn't support version numbers like 10, 10.0, or 10.0.x.
>    Doesn't have wildcard support.
>    Doesn't support version ranges.

2026-06-05 12:14 UTC, cyberbossone-coder requested changes
This user cannot use or change this without permmission